### ISSUE TITLE
iOS simulator amigoclient build failing

### ISSUE THREAD

**Issue by hallahan** [amigocloud/amigoclient#840]

**Comment by hallahan** [comment]
I updated to iOS SDK 10.1 with the new Xcode. I tried to build using the following command:

```
amigomake --all -a i386 -a x86_64 ios -v 10.1
```

I haven't yet found my old iPhone, so I'm going to need to be on the simulator for now. I get the same exact error this time as well.

```
private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/src/tools/apinames.c:19:10: fatal error: 
      'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [/private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/objs/apinames] Error 1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang	  -o /private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/objs/apinames /private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/src/tools/apinames.c 
/private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/src/tools/apinames.c:19:10: fatal error: 
      'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [/private/tmp/build/root/iPhoneSimulator/x86_64/freetype-2.4.10/objs/apinames] Error 1
ERROR: 'build' failed!
ERROR:root:
Traceback (most recent call last):
  File "/usr/local/bin/amigomake", line 168, in main
    action(platform, params)
  File "<string>", line 206, in build
  File "/Users/njh/code/amigomake/src/package.py", line 58, in build
    self._build(platform, env_vars)
  File "/Users/njh/code/amigomake/src/cpackage.py", line 176, in _build
    dep.build(platform)
  File "/Users/njh/code/amigomake/src/external_cpackage.py", line 172, in build
    self._post_build(platform)
  File "/Users/njh/code/amigomake/src/packages.py", line 97, in _post_build
    shutil.move(inc_freetype, inc_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/njh/code/amigoclient/external/install/ios_iPhoneSimulator_x86_64/include/freetype2/freetype'
```

**Comment by hallahan** [comment]
I did end up getting it to build, but it only builds on armv7 and arm64.

This worked:

```
amigomake --all -a armv7 -a arm64 -d ios -v 10.1
```

**Comment by hallahan** [comment]
Though I can get the Xcode build to work. After installing my iOS provision, I'm having cocoa pods problems.

The XCode build fails with:

```
diff: /Users/njh/code/amigoclient/apps/AmigoMobile/ios/AmigoMobile/Pods/../Podfile.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

After installing cocoapods and doing a `pod install`, I then run into a new problem. `pod install` outputs:

```
CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Setup completed
Analyzing dependencies
[!] The dependency `Mixpanel` is not used in any concrete target.
```

Then, when I try to build again in Xcode:

```
clang: error: no such file or directory: '/Users/njh/code/amigoclient/apps/AmigoMobile/ios/AmigoMobile/Pods/Target Support Files/Mixpanel/Mixpanel-dummy.m'
clang: error: no input files
```
